version: '3.8'
services:
  micro_rabbit:
    ports:
      - '5672:5672'
    image: rabbitmq:3.11.4-management
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
    - RABBITMQ_DEFAULT_VHOST=rabbithost
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
  mongo_db:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      -  ./data/mongo:/data/db
  postgres_db:
    image: postgres
    ports:
    - '5333:5432'
    